# Generated by Django 3.0 on 2020-11-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question11',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('par_word', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=200)),
                ('image_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question3',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question4',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=20)),
                ('image_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question5',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=20)),
                ('audio_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question6',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sequence', models.CharField(max_length=20)),
                ('positive_sequence', models.IntegerField()),
                ('audio_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question7',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sequence', models.CharField(max_length=50)),
                ('audio_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question9',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=50)),
                ('audio_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
