# Generated by Django 3.0 on 2020-12-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Q10Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q11_1Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q11_2Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q12Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('sub_score', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q13Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('answer_string', models.CharField(max_length=500, null=True)),
                ('realAnswer_string', models.CharField(max_length=500, null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q1Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
                ('string_from_patient', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Q2Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
                ('filePath', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q4Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q5Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q6Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('normal_audio_filePath', models.TextField(null=True)),
                ('reverse_audio_filePath', models.TextField(null=True)),
                ('normal_text', models.TextField(null=True)),
                ('reverse_text', models.TextField(null=True)),
                ('normal_score', models.IntegerField(null=True)),
                ('reverse_score', models.IntegerField(null=True)),
                ('total_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q7Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('result_sequence', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q8Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
                ('result', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q9_1Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q9_2Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question11',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('par_word', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=200)),
                ('image_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question3',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question4',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=20)),
                ('image_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question5',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=20)),
                ('audio_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question6',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sequence', models.CharField(max_length=20)),
                ('positive_sequence', models.IntegerField()),
                ('audio_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question7',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sequence', models.CharField(max_length=50)),
                ('audio_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question9',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=50)),
                ('audio_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sas_score', models.IntegerField(null=True)),
                ('sds_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
