# Generated by Django 3.0 on 2020-12-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_MOCA_History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('Q1_score', models.IntegerField(null=True)),
                ('Q2_score', models.IntegerField(null=True)),
                ('Q3_score', models.IntegerField(null=True)),
                ('Q4_score', models.IntegerField(null=True)),
                ('Q5_score', models.IntegerField(null=True)),
                ('Q6_1_score', models.IntegerField(null=True)),
                ('Q6_2_score', models.IntegerField(null=True)),
                ('Q7_score', models.IntegerField(null=True)),
                ('Q8_score', models.IntegerField(null=True)),
                ('Q9_score', models.IntegerField(null=True)),
                ('Q10_1_score', models.IntegerField(null=True)),
                ('Q10_2_score', models.IntegerField(null=True)),
                ('total_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='B_Q10_1Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='B_Q10_2Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('end_time', models.CharField(max_length=50, null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='B_Q1Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
                ('string_from_patient', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='B_Q2Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_filePath', models.TextField(null=True)),
                ('first_text', models.TextField(null=True)),
                ('second_filePath', models.TextField(null=True)),
                ('second_text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='B_Q3Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='B_Q4Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('answer_string', models.CharField(max_length=500, null=True)),
                ('realAnswer_string', models.CharField(max_length=500, null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='B_Q5Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
                ('answer_string', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='B_Q6_1Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='B_Q6_2Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='B_Q6_3Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='B_Q7Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('sub_score', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='B_Q8Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='B_Q9Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
    ]
