# Generated by Django 3.0 on 2021-01-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_moca_history',
            name='Q10_file_path1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='Q10_file_path2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='Q3_file_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='Q6_file_path1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='Q6_file_path2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='Q6_file_path3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='Q7_file_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='Q8_file_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='Q9_file_path1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='Q9_file_path2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='Q9_file_path3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='Q9_file_path4',
            field=models.TextField(null=True),
        ),
    ]
