# Generated by Django 2.2.3 on 2020-12-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sas_score', models.IntegerField(max_length=5)),
                ('sds_score', models.IntegerField(max_length=5)),
            ],
        ),
    ]
