# Generated by Django 3.0 on 2021-01-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210103_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_moca_history',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='education',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='b_moca_history',
            name='sex',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
