# Generated by Django 2.2.3 on 2020-12-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='sas_score',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='scale',
            name='sds_score',
            field=models.IntegerField(max_length=20),
        ),
    ]
