# Generated by Django 3.0 on 2020-12-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_b_moca_history_b_q10_1res_b_q10_2res_b_q1res_b_q2res_b_q3res_b_q4res_b_q5res_b_q6_1res_b_q6_2res_b_q'),
    ]

    operations = [
        migrations.DeleteModel(
            name='B_Q2Res',
        ),
        migrations.RemoveField(
            model_name='b_moca_history',
            name='Q2_score',
        ),
    ]
