# Generated by Django 2.2.3 on 2020-12-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201206_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='sas_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scale',
            name='sds_score',
            field=models.IntegerField(),
        ),
    ]
