# Generated by Django 3.0 on 2020-12-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201206_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='sas_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scale',
            name='sds_score',
            field=models.IntegerField(null=True),
        ),
    ]
