# Generated by Django 3.1.2 on 2020-12-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201210_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q10Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q11Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q12Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('sub_score', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q13Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('answer_string', models.CharField(max_length=50, null=True)),
                ('realAnswer_string', models.CharField(max_length=50, null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q1Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
                ('string_from_patient', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Q2Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
                ('filePath', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q4Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q5Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q6Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('normal_audio_filePath', models.TextField(null=True)),
                ('reverse_audio_filePath', models.TextField(null=True)),
                ('normal_text', models.TextField(null=True)),
                ('reverse_text', models.TextField(null=True)),
                ('normal_score', models.IntegerField(null=True)),
                ('reverse_score', models.IntegerField(null=True)),
                ('total_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q7Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q8Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q9Res',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filePath', models.TextField(null=True)),
                ('audio_to_text', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scale',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
